FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY .env.local .env

COPY . .


RUN npm run build


# Install serve
RUN npm install -g serve 

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
